Update patch set 1
Patch Set 1:

Dunno what I'm doing wrong here, but I'm getting errors:

kernel/asus/grouper/drivers/cpufreq/cpufreq_ondemand.c:950:2: error: implicit declaration of function 'lock_policy_rwsem_write' [-Werror=implicit-function-declaration]
kernel/asus/grouper/drivers/cpufreq/cpufreq_ondemand.c:969:3: error: implicit declaration of function 'unlock_policy_rwsem_write' [-Werror=implicit-function-declaration]

Right now I *THINK* I have the right order, based on what depends on what, but I'm not even sure exactly.  I applied them like this:

 cpufreq: ondemand: increase 2phase screen off lp frequency
 cpufreq: ondemand: add power_save_bias screen off override
 cpufreq: ondemand: adjust default parameters
 [CPUFREQ] CPUfreq ondemand: update sampling rate without waiting for next sampling
 cpufreq: ondemand: set 2phase to 204Mhz if lp && screen off
 cpufreq: ondemand: add earlysuspend/lateresume drivers
 cpufreq: ondemand: update comments
 cpufreq: ondemand: 2phase: check for lp instead of online cpus
 cpufreq: ondemand: 2phase: double the counter if we have limited the freq
 cpufreq: ondemand: limit 2phase freq to max lpcpu if only one cpu is online
 drivers: cpufreq: ondemand: add touchpoke & 2phase.

Paul, is there a way to consolidate these cpufreq patches into fewer single-purpose ones w/a detailed description of what it does... ("touchpoke"?)

Patch-set: 1